version: '3.9'

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: usrAdmin
            MONGO_INITDB_ROOT_PASSWORD: xE!4IsEt#i4IzA8riAg
        networks:
            - prod
        ports: 
            - 27017:27017

    rabbitmq:
        image: rabbitmq:3.11-management
        restart: always
        networks:
            - prod
        ports: 
            - 15672:15672
    
    directoryapi:
        build:
            dockerfile: src/TelephoneDirectory.Directory/TelephoneDirectory.Directory.API/Dockerfile
        restart: always
        depends_on:
            - mongo
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        networks:
            - prod
        ports: 
            - 8081:80

    reportapi:
        build:
            dockerfile: src/TelephoneDirectory.Report/TelephoneDirectory.Report.API/Dockerfile
        restart: always
        depends_on:
            - mongo
            - rabbitmq
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        networks:
            - prod
        ports: 
            - 8082:80
        
    reportconsumer:
        build:
            dockerfile: src/TelephoneDirectory.Consumer/TelephoneDirectory.Consumer.Report/Dockerfile
        restart: always
        depends_on:
            - mongo
            - rabbitmq
            - directoryapi
            - reportapi
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        networks:
            - prod
        ports: 
            - 8083:80
        
networks:
    prod: